# Site
name: "dietReviews"
title: "dietReviews"
description: "건강하고 활기차고 효율적인 다이어트를 위한 모든 것!"
logo: 'assets\images\android-chrome-512x512.png'
favicon: 'assets\images\android-chrome-512x512.png'
baseurl: /dietReviews
# google_analytics: "G-P4PN9F3D1X"
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
url: "https://oneido.github.io/dietReviews"
# email: wowthemesnet@gmail.com

# Authors
authors:
  exercise:
    name: exercise
    display_name: 멋진 다이어터
    avatar: 'assets\images\exercise.svg'
    # email: wowthemesnet@gmail.com
    web: https://oneido.github.io/dietReviews
    # twitter: https://twitter.com/wowthemesnet
    description: "뿜어져 나오는 건강미는 운동과 함께!"
  food:
    name: food
    display_name: 건강한 다이어터    
    avatar: 'assets\images\food.svg'
    # email: wowthemesnet@gmail.com
    web: https://oneido.github.io/dietReviews
    # twitter: https://twitter.com/wowthemesnet
    description: "자기 학대는 좋지 않아요. 나를 사랑하는 법은 건강하게 먹기!"
  motivation:
    name: motivation
    display_name: 변화하는 다이어터
    avatar: 'assets\images\motivation-avatar.png'
    # email: wowthemesnet@gmail.com
    web: https://oneido.github.io/dietReviews
    # twitter: https://twitter.com/wowthemesnet
    description: "다양한 이야기를 통해 더 나은 자신으로 변화하세요." 
  fun:
    name: fun
    display_name: 즐기는 다이어터
    avatar: 'assets\images\fun.svg'
    # email: wowthemesnet@gmail.com
    web: https://oneido.github.io/dietReviews
    # twitter: https://twitter.com/wowthemesnet
    description: "스트레스 없는 다이어트는 없어요. 우리 지지 말고 웃으며 힘내요."
  idea:
    name: idea
    display_name: 생각하는 다이어터
    avatar: 'assets\images\idea.svg'
    # email: wowthemesnet@gmail.com
    web: https://oneido.github.io/dietReviews
    # twitter: https://twitter.com/wowthemesnet
    description: "다이어트에 관련한 아이디어를 참고하세요."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
