# Site
name: "dietReviews"
title: "dietReviews"
description: "건강하고 활기차고 효율적인 다이어트를 위한 모든 것!"
logo: 'assets\images\android-chrome-512x512.png'
favicon: 'assets\images\android-chrome-512x512.png'
baseurl: /dietReviews
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
# email: wowthemesnet@gmail.com

# Authors
authors:
  exercise:
    name: exercise
    display_name: 멋진 다이어터
    avatar: 'assets/images/exercise-avatar.png'
    # email: wowthemesnet@gmail.com
    web: https://oneido.github.io/dietReviews
    # twitter: https://twitter.com/wowthemesnet
    description: "뿜어져 나오는 건강미는 운동과 함께!"
  food:
    name: food
    display_name: 건강한 다이어터    
    avatar: 'assets/images/food-avatar.png'
    # email: wowthemesnet@gmail.com
    web: https://oneido.github.io/dietReviews
    # twitter: https://twitter.com/wowthemesnet
    description: "자기 학대는 좋지 않아요. 나를 사랑하는 법은 건강하게 먹기!"
  motivation:
    name: motivation
    display_name: 도전하는 다이어터
    avatar: 'assets/images/motivation-avatar.png'
    # email: wowthemesnet@gmail.com
    web: https://oneido.github.io/dietReviews
    # twitter: https://twitter.com/wowthemesnet
    description: "뿜어져 나오는 건강미는 운동과 함께!"
  fun:
    name: fun
    display_name: 즐기는 다이어터
    avatar: 'assets/images/avatar-sal.png'
    # email: wowthemesnet@gmail.com
    web: https://oneido.github.io/dietReviews
    # twitter: https://twitter.com/wowthemesnet
    description: "스트레스 없는 다이어트는 없어요. 우리 지지 말고 웃으며 힘내봐요."
  story:
    name: story
    display_name: 이야기하는 다이어터
    avatar: 'assets/images/avatar-sal.png'
    # email: wowthemesnet@gmail.com
    web: https://oneido.github.io/dietReviews
    # twitter: https://twitter.com/wowthemesnet
    description: "다른 사람은 어떻게 다이어트를 하나? 참고할 것은 참고하고 배울 것은 배워봐요."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
